# Run docker-compose -f docker-compose-local.py build
# Run docker-compose -f docker-compose-local.py up
# Comments represent alternate or optional configurations

version: '2.1'

services:
  postgres:
   container_name: postgresql_container
   restart: always
   build: ./postgresql
   volumes:
     - /var/lib/postgresql
   ports:
     - "5432:5432"
   env_file:
     - .env_docker
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 10s
     timeout: 5s
     retries: 5

  redis:
    container_name: redis_container
    restart: always
    image: redis
#    volumes:
#      - [path to custom redis.conf file]:/usr/local/etc/redis/redis.conf
    ports:
    - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
